# Generated by Django 2.1.1 on 2018-09-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('data_nasc', models.DateField()),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
