# Generated by Django 2.1.1 on 2018-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_aluno_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
